### PR TITLE
Signing and Signup page redesign

### PR DESCRIPTION
**Pull request by Abhii5496**
Re-Design and Develop Login and Signup page with responsive layout #51

### CODE REVIEW

**Comment by Abhii5496** [comment]
@yesahem check and merge .

**Comment by yesahem** [comment]
looks cool @Abhii5496 thanks for you contribution!!
Happy Coding 

Will merge this soon !!

**Comment by Abhii5496** [comment]
> looks cool @Abhii5496 thanks for you contribution!! Happy Coding
> 
> Will merge this soon !!

I have a suggestion , Don't push your code directly  before merging all pr . It leads to conflict .
(add relevant labels to this pr)

**Comment by yesahem** [comment]
@Abhii5496 Thanks !!

**Pull request merged**
