### PR TITLE
Add Dark Mode Toggle with Persistent State Across All Pages

### PR DESCRIPTION
**Pull request by HackesticMedusa**
This pull request introduces a Dark Mode toggle feature to the application. The toggle functionality has been implemented across all pages, ensuring a consistent user experience. Additionally, the selected mode (dark or light) is remembered using localStorage, so the user's preference persists even after refreshing the page or navigating to different sections of the site.

Key changes include:
- Added `DarkModeToggle` component to all relevant pages.
- Implemented `useEffect` to check and apply the saved theme from localStorage.
- Updated CSS to support dark mode styling.
- Ensured the toggle state is synchronized across different components and routes.

This enhancement improves the user experience by providing a customizable and persistent theme setting.

### CODE REVIEW

**Comment by yesahem** [comment]
> This pull request introduces a Dark Mode toggle feature to the application. The toggle functionality has been implemented across all pages, ensuring a consistent user experience. Additionally, the selected mode (dark or light) is remembered using localStorage, so the user's preference persists even after refreshing the page or navigating to different sections of the site.
> 
> Key changes include:
> 
> * Added `DarkModeToggle` component to all relevant pages.
> * Implemented `useEffect` to check and apply the saved theme from localStorage.
> * Updated CSS to support dark mode styling.
> * Ensured the toggle state is synchronized across different components and routes.
> 
> This enhancement improves the user experience by providing a customizable and persistent theme setting.

Please make a separate branch for the issue make another PR 
I guess you haven't read the README.md file from the home page 
Kindly ready it for contributions

**Comment by yesahem** [comment]
more fixing needed 
there are some pages which is not switched to dark mode even when the dark mode is enabled kindly fix these
 
Screenshot 2024-10-02 at 11 26 54 AM
file: Header.tsx

Screenshot 2024-10-02 at 11 26 41 AM

file: uploadBlog.tsx

Screenshot 2024-10-02 at 11 26 33 AM
onto the dashboard page even in the dark mode this font is not set to dark mode 


Please add these changes to the Darkmode to make it more polished


BTW nice PR

**Review by yesahem — COMMENTED** [review]
Dark mode toggle is not persistence across all the pages 

BlogUpload route doesn't have the dark mode feature 

headers are not in dark mode

**Comment by HackesticMedusa** [comment]
Okay, I'm working on it and try to fix it

**Comment by yesahem** [comment]
> Okay, I'm working on it and try to fix it

All the best 
Make sure to maintain a separate branch for issues in format <strong> issue/issue-number</strong>

**Comment by HackesticMedusa** [comment]
Can I connect with you in LinkedIn?

**Comment by yesahem** [comment]
> Can I connect with you in LinkedIn?

Connect to my twitter x.com/heyshishu

**Comment by HackesticMedusa** [comment]
Okay sir, thank you

**Comment by yesahem** [comment]
> Okay sir, thank you

have you read this before contribution ??

Please follow the format before creating PR 

Screenshot 2024-10-02 at 1 39 28 PM


Make a separate branch and then create PR from the branch 

you all changes are nice so just do this one step

**Comment by HackesticMedusa** [comment]
So I repeat the previous changes? Also I had messaged you in Twitter please check

**Comment by HackesticMedusa** [comment]
> > Okay sir, thank you
> 
> have you read this before contribution ??
> 
> Please follow the format before creating PR
> 
> Screenshot 2024-10-02 at 1 39 28 PM
> Make a separate branch and then create PR from the branch
> 
> you all changes are nice so just do this one step

Hello,

I’ve submitted another PR. Could you please review it when you have a moment? Here’s the link: https://github.com/yesahem/Medium-Blog/pull/19.

You can close this PR if you want.

Thank you!

**Pull request merged**
