### PR TITLE
Add Dark Mode Toggle with Persistent State Across All Pages

### PR DESCRIPTION
**Pull request by HackesticMedusa**
This pull request introduces a Dark Mode toggle feature to the application. The toggle functionality has been implemented across all pages, ensuring a consistent user experience. Additionally, the selected mode (dark or light) is remembered using localStorage, so the user's preference persists even after refreshing the page or navigating to different sections of the site.

**Key Changes:**
- Added `DarkModeToggle` component to all relevant pages.
- Implemented `useEffect` to check and apply the saved theme from localStorage.
- Updated CSS to support dark mode styling.
- Ensured the toggle state is synchronized across different components and routes.

This enhancement improves the user experience by providing a customizable and persistent theme setting.

Issue Number: #16

home
signup
signin
blogs
upload_blog

### CODE REVIEW

**Comment by yesahem** [comment]
Looks good @HackesticMedusa

**Comment by yesahem** [comment]
Fix this issue asap @HackesticMedusa 

Screenshot 2024-10-03 at 12 12 14 AM

**Comment by yesahem** [comment]
Still not able to get the dark mode on Home and Blog routes 

Screenshot 2024-10-03 at 12 22 33 AM
Home Route


Screenshot 2024-10-03 at 12 23 37 AM

Blog Route

Also in the footer
Screenshot 2024-10-03 at 12 30 36 AM

**Comment by yesahem** [comment]
Fix this @HackesticMedusa

**Comment by HackesticMedusa** [comment]
> Fix this @HackesticMedusa

I'll try to fix from my end also here is a small request kindly mark the pull/merge request with "hacktoberfest-accepted" label it'll be much appreciated. Thank you.

**Comment by HackesticMedusa** [comment]
> Fix this @HackesticMedusa

I’ll do my best to address the issue from my side. If it’s not too much trouble, could you please mark the pull/merge request with the “hacktoberfest-accepted” label? I would greatly appreciate it. Thank you so much!

**Comment by yesahem** [comment]
any updates @HackesticMedusa

**Comment by HackesticMedusa** [comment]
> any updates @HackesticMedusa

Not yet, also you haven't added “hacktoberfest-accepted” label till now.

**Comment by yesahem** [comment]
Done do it asap now @HackesticMedusa

**Pull request merged**
