### PR TITLE
feat: add modular design to BE & further improvement in FE.

### LINKED ISSUE #21: feat: use modular approach in hono.js
### Setup in backend:
- [x] Controllers
- [x] Middlewares
- [x] Routes
- [x] Added Delete Blog Route

### Setup in frontend:
- [x] Solved Frontend Blog Creation Issue
- [x] Added View Blog Page Component

Overall resulting in improving the code structure.

@yesahem Can you please add it under hacktoberfest label.

### PR DESCRIPTION
**Pull request by geekyharsh05**
### Setup in backend:
- [x] Controllers
- [x] Middlewares
- [x] Routes
- [x] Added Delete Blog Route

### Setup in frontend:
- [x] Solved Frontend Blog Creation Issue
- [x] Added View Blog Page Component

Resolves: #21 

### SignUp
Screenshot 2024-10-09 at 6 47 43 PM

### SignIn
Screenshot 2024-10-09 at 6 47 55 PM

### Get User Info
Screenshot 2024-10-09 at 6 48 27 PM

### Create Post
Screenshot 2024-10-09 at 6 49 37 PM

### Update Post
Screenshot 2024-10-09 at 6 59 22 PM

### Get All Posts
Screenshot 2024-10-09 at 6 50 32 PM

### Get Posts By Id
Screenshot 2024-10-09 at 9 49 05 PM

### Delete Post
Screenshot 2024-10-09 at 7 07 54 PM

### Blog Page
Screenshot 2024-10-09 at 9 51 17 PM

### Create Blog
Screenshot 2024-10-09 at 9 52 08 PM

### Blog Created Successfully
Screenshot 2024-10-09 at 9 52 30 PM

### View Blog
Screenshot 2024-10-09 at 9 53 09 PM

### CODE REVIEW

**Comment by geekyharsh05** [comment]
@yesahem Can you please review it?

**Comment by geekyharsh05** [comment]
@yesahem I have added an env.ts file in frontend, which you can change when you are deploying it to production. Change the url everywhere to `PROD` URL.

**Comment by yesahem** [comment]
As per the screenshots it looks awesome bro but currently I ma stuck between exams so will be able to look at the code on Sunday or Monday max . Hope you understands @geekyharsh05

**Comment by geekyharsh05** [comment]
> As per the screenshots it looks awesome bro but currently I ma stuck between exams so will be able to look at the code on Sunday or Monday max . Hope you understands @geekyharsh05 

No problem

**Comment by yesahem** [comment]
@geekyharsh05  Changes makes sense to me as of now 

Merging !!! 
Congratulations ✨ 
Thanks 🎉
(Will improve it more on the fly) 🚀

**Pull request merged**
