### PR TITLE
added the password hashing function

### PR DESCRIPTION
**Pull request by himanshuranjan007**
Create the password hashing function for the user signup.

### CODE REVIEW

**Comment by yesahem** [comment]
Please fix some issue :-
      1. Please refer to issue number while creating a PR
       
      2. 
Screenshot 2024-10-06 at 3 52 55 PM

      Fix the password and email message separately 
      

       3.        
Screenshot 2024-10-06 at 3 53 31 PM

upgrade the salt from 4 to at least 6 or more and please don't remove the console log as of now Only comment it out 

Fix these and then create a PR @himanshuranjan007

**Comment by yesahem** [comment]
any update @himanshuranjan007

**Comment by pandeyashu08** [comment]
@yesahem @geekyharsh05  It is a bad idea to do validations and hashing in client side instead we should do these things on server side.
Refer: #44

**Comment by geekyharsh05** [comment]
@pandeyashu08 Makes a lot of sense. Nice work.

**Comment by geekyharsh05** [comment]
@himanshuranjan007 Any updates?

**Pull request closed without merging**
