### PR TITLE
fix: improved theme toggle by replacing text with an icon

### LINKED ISSUE #34: Improve UI for Theme Toggle: Use Icon Instead of Text
Currently, the theme toggle is displayed as text ("Dark Mode"). To enhance the user experience and make the UI more intuitive, I suggest replacing the "Dark Mode" text with a theme icon (e.g., a sun/moon). This will make it visually cleaner and more in line with modern design practices.

image

### PR DESCRIPTION
**Pull request by shanksxz**
## Description
Replaced the "Dark Mode" text with a theme icon (sun/moon) for better UI consistency and modern design.

## Screenshots
Before:
image

After:
image

## Related Issues
Closes #34 

## Testing
- Manually tested the theme toggle to ensure proper functionality in both dark and light modes.

## Notes
- No changes in functionality, purely a UI improvement.

### CODE REVIEW

**Comment by yesahem** [comment]
Add the Darktheme to footer component also @shanksxz

**Comment by shanksxz** [comment]
hmm?
https://github.com/user-attachments/assets/f2d5c087-2c88-4a2e-9575-83f63133c948

**Comment by yesahem** [comment]
> hmm? https://github.com/user-attachments/assets/f2d5c087-2c88-4a2e-9575-83f63133c948

Bro why you gave the footer a separate toggle button 

😂😂😂

It looks so funny BTW 
Please conditionally render the footer with the above toggle button (Button on the header)


What do you say @geekyharsh05 ??

**Comment by shanksxz** [comment]
> > hmm? https://github.com/user-attachments/assets/f2d5c087-2c88-4a2e-9575-83f63133c948
> 
> Bro why you gave the footer a separate toggle button 
> 
> 😂😂😂
> 
> It looks so funny BTW 
> Please conditionally render the footer with the above toggle button (Button on the header)
> 
> 
> What do you say @geekyharsh05 ??

Ohh! I thought you asked to add button to footer, my bad

**Comment by yesahem** [comment]
> > > hmm? https://github.com/user-attachments/assets/f2d5c087-2c88-4a2e-9575-83f63133c948
> > 
> > 
> > Bro why you gave the footer a separate toggle button
> > 😂😂😂
> > It looks so funny BTW
> > Please conditionally render the footer with the above toggle button (Button on the header)
> > What do you say @geekyharsh05 ??
> 
> Ohh! I thought you asked to add button to footer, my bad

I mean to say that when dark mode is toggled then footer doesn't have any impact of dark mode on it so make an effect on footer too 


Sorry for not being more clear to you !!!
Hope now you got it !!

**Comment by geekyharsh05** [comment]
@shanksxz Agree, remove it from the footer and just have it in the header. It'll be better. Thanks for your efforts.

**Comment by shanksxz** [comment]
> > > > hmm? https://github.com/user-attachments/assets/f2d5c087-2c88-4a2e-9575-83f63133c948
> > > 
> > > 
> > > Bro why you gave the footer a separate toggle button
> > > 😂😂😂
> > > It looks so funny BTW
> > > Please conditionally render the footer with the above toggle button (Button on the header)
> > > What do you say @geekyharsh05 ??
> > 
> > 
> > Ohh! I thought you asked to add button to footer, my bad
> 
> I mean to say that when dark mode is toggled then footer doesn't have any impact of dark mode on it so make an effect on footer too
> 
> Sorry for not being more clear to you !!! Hope now you got it !!

have u checked now?

**Comment by yesahem** [comment]
Please add consistency in colors of footer and body @shanksxz btw it looks cool else it is good too go 🚀🚀🚀

Screenshot 2024-10-13 at 11 55 18 PM

**Comment by shanksxz** [comment]
> Please add consistency in colors of footer and body @shanksxz btw it looks cool else it is good too go 🚀🚀🚀
> 
> Screenshot 2024-10-13 at 11 55 18 PM
> 

doesn't this look much better?

**Comment by yesahem** [comment]
> > Please add consistency in colors of footer and body @shanksxz btw it looks cool else it is good too go 🚀🚀🚀
> > Screenshot 2024-10-13 at 11 55 18 PM
> 
> doesn't this look much better?

Add it to the header and body of all routes too !!!(this is what I mean to say make colors of all the section consistent)
your colour looks more pleasing

**Comment by yesahem** [comment]
any update @shanksxz 
looking for mergin it asap so please quick fix the colors and make a commit asap 
thanks for your efforts....

**Comment by shanksxz** [comment]
> any update @shanksxz 
> looking for mergin it asap so please quick fix the colors and make a commit asap 
> thanks for your efforts....

Lil bit busy, will make an pr by tonight

**Comment by yesahem** [comment]
> > any update @shanksxz
> > looking for mergin it asap so please quick fix the colors and make a commit asap
> > thanks for your efforts....
> 
> Lil bit busy, will make an pr by tonight

no issues

**Comment by shanksxz** [comment]
@yesahem can u resolve merge conflict or should i do from my end?

**Comment by yesahem** [comment]
> @yesahem can u resolve merge conflict or should i do from my end?

Resolve the merge conflict please @shanksxz

**Comment by shanksxz** [comment]
@yesahem i can't from side, maybe i will have to do an new fork

**Comment by yesahem** [comment]
> @yesahem i can't from side, maybe i will have to do an new fork

will update you tomorrow about creating a new fork or not 

Resolving conflicts from our side

**Comment by yesahem** [comment]
@shanksxz bhai closing this PR as of now please make a fresh fork and add the changes 
Thanks for the contribution!!

**Pull request closed without merging**
